import { HarmonyClassDescriptor } from './harmonyTypes';

export const HARMONY_CATALOG: HarmonyClassDescriptor[] = [
  {
    id: 'analogous',
    name: 'Analogous',
    description: 'Colors that are next to each other on the color wheel. Creates a serene and comfortable design.',
    tags: ['classic', 'calm', 'nature'],
    recommendedUseCases: ['Backgrounds', 'Subtle UI', 'Nature themes'],
    supportedVariants: ['standard', 'soft', 'vivid'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'split-analogous',
    name: 'Split-Analogous',
    description: 'A variation of analogous that skips a color, offering more contrast while maintaining harmony.',
    tags: ['modern', 'balanced'],
    recommendedUseCases: ['Web design', 'App interfaces'],
    supportedVariants: ['standard', 'soft', 'vivid'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'complementary',
    name: 'Complementary',
    description: 'Colors opposite each other on the color wheel. High contrast and high impact.',
    tags: ['classic', 'high-contrast', 'bold'],
    recommendedUseCases: ['Call to action buttons', 'Logos', 'Vibrant UI'],
    supportedVariants: ['balanced', 'bold', 'subtle'],
    defaultVariant: 'balanced',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'split-complementary',
    name: 'Split-Complementary',
    description: 'Uses a base color and the two colors adjacent to its complement. Less tension than complementary.',
    tags: ['versatile', 'balanced'],
    recommendedUseCases: ['Illustrations', 'Marketing materials'],
    supportedVariants: ['balanced', 'bold', 'subtle'],
    defaultVariant: 'balanced',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'triadic',
    name: 'Triadic',
    description: 'Three colors evenly spaced around the color wheel. Vibrant even if pale or unsaturated.',
    tags: ['vibrant', 'energetic'],
    recommendedUseCases: ['Playful designs', 'Childrens products', 'Creative UI'],
    supportedVariants: ['calm', 'active', 'energetic'],
    defaultVariant: 'active',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'tetradic',
    name: 'Tetradic (Double Complementary)',
    description: 'Four colors arranged into two complementary pairs. Rich and complex.',
    tags: ['complex', 'rich'],
    recommendedUseCases: ['Complex illustrations', 'Data visualization'],
    supportedVariants: ['balanced', 'bold', 'subtle'],
    defaultVariant: 'balanced',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'square',
    name: 'Square',
    description: 'Four colors spaced evenly around the color wheel.',
    tags: ['balanced', 'vibrant'],
    recommendedUseCases: ['Dynamic UI', 'Brand identity'],
    supportedVariants: ['balanced', 'bold', 'subtle'],
    defaultVariant: 'balanced',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    description: 'Variations in lightness and saturation of a single color.',
    tags: ['clean', 'minimal', 'elegant'],
    recommendedUseCases: ['Minimalist UI', 'Corporate branding', 'Data heavy apps'],
    supportedVariants: ['minimal', 'rich', 'high-range'],
    defaultVariant: 'rich',
    minSize: 5,
    maxSize: 12,
  },
  {
    id: 'neutral',
    name: 'Neutral',
    description: 'Muted, low-saturation colors that provide a sophisticated backdrop.',
    tags: ['sophisticated', 'muted', 'calm'],
    recommendedUseCases: ['Luxury brands', 'Editorial', 'Backgrounds'],
    supportedVariants: ['standard', 'soft', 'rich'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'accent-led',
    name: 'Accent-Led',
    description: 'A mostly neutral palette with one strong, vibrant accent color.',
    tags: ['modern', 'focused', 'ui-friendly'],
    recommendedUseCases: ['SaaS dashboards', 'Product UI', 'Landing pages'],
    supportedVariants: ['standard', 'bold', 'subtle'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'warm-shift',
    name: 'Warm Shift',
    description: 'Shifts the base color towards warmer hues (reds, oranges, yellows).',
    tags: ['warm', 'inviting', 'energetic'],
    recommendedUseCases: ['Food apps', 'Social media', 'Creative portfolios'],
    supportedVariants: ['standard', 'soft', 'vivid'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'cool-shift',
    name: 'Cool Shift',
    description: 'Shifts the base color towards cooler hues (blues, greens, purples).',
    tags: ['cool', 'professional', 'calm'],
    recommendedUseCases: ['Finance apps', 'Healthcare', 'Corporate sites'],
    supportedVariants: ['standard', 'soft', 'vivid'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'editorial',
    name: 'Editorial',
    description: 'High-contrast, sophisticated pairings inspired by print magazines.',
    tags: ['sophisticated', 'print', 'high-contrast'],
    recommendedUseCases: ['Blogs', 'News sites', 'Fashion brands'],
    supportedVariants: ['standard', 'bold', 'minimal'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'brand-classic',
    name: 'Brand Classic',
    description: 'A reliable, balanced palette suitable for traditional corporate branding.',
    tags: ['reliable', 'corporate', 'balanced'],
    recommendedUseCases: ['B2B websites', 'Corporate identity'],
    supportedVariants: ['standard', 'rich', 'subtle'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'vibrant-modern',
    name: 'Vibrant Modern',
    description: 'High-saturation, high-energy colors popular in modern tech startups.',
    tags: ['tech', 'startup', 'energetic'],
    recommendedUseCases: ['Tech products', 'Marketing sites', 'App icons'],
    supportedVariants: ['standard', 'vivid', 'bold'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'muted-modern',
    name: 'Muted Modern',
    description: 'Desaturated, complex colors that feel contemporary and grounded.',
    tags: ['contemporary', 'grounded', 'desaturated'],
    recommendedUseCases: ['Lifestyle brands', 'DTC products', 'Portfolios'],
    supportedVariants: ['standard', 'soft', 'rich'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'pastel-system',
    name: 'Pastel System',
    description: 'Light, low-saturation colors that feel soft and approachable.',
    tags: ['soft', 'approachable', 'light'],
    recommendedUseCases: ['Health & wellness', 'Childrens brands', 'Spring campaigns'],
    supportedVariants: ['standard', 'soft', 'vivid'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'earth-tone',
    name: 'Earth Tone',
    description: 'Colors inspired by nature: browns, greens, warm grays, and muted reds.',
    tags: ['nature', 'organic', 'warm'],
    recommendedUseCases: ['Eco-friendly brands', 'Outdoor gear', 'Coffee shops'],
    supportedVariants: ['standard', 'rich', 'muted'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'dark-mode-first',
    name: 'Dark Mode First',
    description: 'Optimized for dark backgrounds, featuring deep shades and luminous accents.',
    tags: ['dark', 'luminous', 'tech'],
    recommendedUseCases: ['Developer tools', 'Gaming apps', 'Night mode UI'],
    supportedVariants: ['standard', 'high-contrast', 'subtle'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'accessibility-first',
    name: 'Accessibility First',
    description: 'Prioritizes high contrast ratios to ensure maximum readability (WCAG AAA).',
    tags: ['accessible', 'inclusive', 'high-contrast'],
    recommendedUseCases: ['Government sites', 'Healthcare', 'Public services'],
    supportedVariants: ['standard', 'high-contrast'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  },
  {
    id: 'ui-product-system',
    name: 'UI Product System',
    description: 'A comprehensive set of colors designed specifically for complex web applications.',
    tags: ['ui', 'system', 'comprehensive'],
    recommendedUseCases: ['SaaS', 'Dashboards', 'Admin panels'],
    supportedVariants: ['standard', 'soft', 'bold'],
    defaultVariant: 'standard',
    minSize: 7,
    maxSize: 12,
  },
  {
    id: 'semantic',
    name: 'Semantic / Role-Based',
    description: 'Generates colors based on their meaning (success, warning, error, info).',
    tags: ['semantic', 'functional', 'ui'],
    recommendedUseCases: ['Alerts', 'Status indicators', 'Forms'],
    supportedVariants: ['standard', 'soft', 'vivid'],
    defaultVariant: 'standard',
    minSize: 5,
    maxSize: 9,
  }
];
